const String URL_LANE_TO_TRACKS =
    'http://jhshim.ddns.net/api/lanetotracks/?format=json';
const String URL_NODE_OF_LANES =
    'http://jhshim.ddns.net/api/nodeoflanes/?format=json';
const String URL_POS_OF_BUSES =
    'http://jhshim.ddns.net/api/posofbuses/?format=json';
const String URL_ULSAN_BUS_LANE_TO_TRACKS =
    'http://jhshim.ddns.net/api/ulsanbus_lanetotracks/?format=json';
const String URL_ULSAN_BUS_TIME_TABLES =
    'http://jhshim.ddns.net/api/ulsanbus_timetables/?format=json';
const String URL_ULSAN_BUS_NODE_TO_TRACKS =
    'http://jhshim.ddns.net/api/ulsanbus_nodetotracks/?format=json';
const String URL_ULSAN_BUS_ARRIVAL_INFOS =
    'http://jhshim.ddns.net/api/ulsanbus_arrivalinfos/?format=json';
const String URL_LANE_ALIASES =
    'http://jhshim.ddns.net/api/lanealiases/?format=json';
const String URL_PART_OF_LANES =
    'http://jhshim.ddns.net/api/partoflanes/?format=json';
const String URL_MAP_TO_ALIASES =
    'http://jhshim.ddns.net/api/maptoaliases/?format=json';
const String URL_LANDMARK_ALIASES =
    'http://jhshim.ddns.net/api/landmarkaliases/?format=json';
const String URL_LANDMARK_NODES =
    'http://jhshim.ddns.net/api/landmarknodes/?format=json';
const String URL_LANDMARK_OF_LANES =
    'http://jhshim.ddns.net/api/landmarkoflanes/?format=json';

const int N_BUS_MAX = 14;
const int N_BUS_MIN = 1;
